### PR TITLE
Milestone 1 - React app setup

### PR DESCRIPTION
**Pull request by uryelah**
Hey there! 👋 
In this milestone I:

- used create-react-app to initialize a new React app

- cleaned up unused images from the default project

- installed prop-types via npm

- installed big-js via npm

- added linting files

- pushed the app to [Heroku](https://microverse-701-calculator.herokuapp.com/)

Thanks for taking your time reviewing this project 🦄

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @uryelah  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this milestone :+1: just one more thing to do.
 **You need to add linter's check to this milestone before it can be approved** 👇
image
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/54883773/

 Add linter's check and fix all errors, check out this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
image
If you are not having this check on your `Github` page, kindly visit :point_right:[ linter set up](https://github.com/microverseinc/linters-config/blob/master/ruby/.stickler.yml)

You seem to have the config files already. Let's make sure stickler is ON for this repo on https://stickler-ci.com/


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by uryelah** [comment]
@bellom Hey Bello, thanks for noticing it.
I kind seem to make stickler work for this PR as I added the files after creating it. I'll have to make a new one to make it work.

**Comment by uryelah** [comment]
Stickler active and at all speed 🚋 !

**Review by Oghenebrume50 — APPROVED** [review]
### STATUS: APPROVED 

Hi @uryelah  this looks good now, kudos for making changes :+1:  please merge and move on to the next milestone, **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

**Pull request merged**
